### ISSUE TITLE
Add button to "Export Warnings" as Text File

### ISSUE THREAD

**Issue by latenitefilms** [latenitefilms/Capacitor#2]
This stuff:

<img width="765" alt="image" src="https://github.com/latenitefilms/Capacitor/assets/22286696/db402086-a2d8-47d1-b52d-9e0603405bc6">

**Comment by randomeizer** [comment]
What warnings? There ones listed in the box?

**Comment by latenitefilms** [comment]
Yeah exactly, everything in the text box. Kinda the same as Adobe Media Encoder does when doing OP59 compliant audio, or exporting a FCP7 XML if there's issues.

**Comment by randomeizer** [comment]
This might actually be a bit tricky if using the SwiftUI `fileExport` API, unless we can output  more than one file simultaneously.

It could be added as a sidecar file in the bundle version though, although nobody would ever see it...

**Comment by latenitefilms** [comment]
Worse case, it could just pop up another save dialog? Alternatively we MIGHT be able to assign a .txt file as a sidecar file for .fcpxml so that we can create a new .txt file next to it whilst in sandbox. You can refer to BRAW Toolbox to see how we read sidecar files.

**Comment by latenitefilms** [comment]
Actually, probably just quickest/easiest solution is to have a separate "Export Warnings" button - keep things simple. Uses the same path as the last FCPXML Export.

**Comment by randomeizer** [comment]
The other thing is that currently, it doesn't detect which actual data was dropped, just lists what could be lost.

**Comment by latenitefilms** [comment]
Hmmm, that's a good point. It probably doesn't matter for v1, but detecting what data was actually dropped would be handy.

**Comment by latenitefilms** [comment]
This has been actioned.
